modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[dependencies.sandexplosion]]
    modId="forge"
    mandatory=true
    versionRange="[47.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sandexplosion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[mods]]
modId="sandexplosion"
version="1.0.0"
displayName="Sand Explosion"
description="Sand placed on dirt or grass explodes!"
